-- MySQL Script generated by MySQL Workbench
-- nie, 29 kwi 2018, 07:47:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Kolor_profili`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Kolor_profili` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Kolor_profili` (
  `id` INT NOT NULL,
  `nazwy_k_p` VARCHAR(45) NOT NULL,
  `doplata_do_k_p` DOUBLE(6,2) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`Model_produktu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Model_produktu` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Model_produktu` (
  `id` INT NOT NULL,
  `nazwa_modelu` VARCHAR(45) NULL,
  `doplata_do_modelu` DOUBLE(6,2) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`Typy_montazu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Typy_montazu` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Typy_montazu` (
  `id` INT NOT NULL,
  `nazwa_typu` VARCHAR(45) NOT NULL,
  `doplata_m` DOUBLE(6,2) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`Materialy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Materialy` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Materialy` (
  `id` INT NOT NULL,
  `nazwy_mat` VARCHAR(45) NOT NULL,
  `doplata_mat` DOUBLE(6,2) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`Produkt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Produkt` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Produkt` (
  `id` INT NOT NULL,
  `nazwa` VARCHAR(45) NULL,
  `szer` INT NULL,
  `wys` INT NULL,
  `cenabazowa` DOUBLE(6,2) NOT NULL,
  `ilosc` INT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`Wycena`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Wycena` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Wycena` (
  `cena_final` DECIMAL(10,2) NOT NULL,
  `data_wyceny` DATE NOT NULL,
  PRIMARY KEY (`cena_final`));


-- -----------------------------------------------------
-- Table `mydb`.`Konfigurator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Konfigurator` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Konfigurator` (
  `id` INT NOT NULL,
  `Kolor_id` INT NOT NULL,
  `Model_id` INT NOT NULL,
  `Typy_montazu_id` INT NOT NULL,
  `Materialy_id` INT NOT NULL,
  `Produkt_id` INT NOT NULL,
  `Wycena_cena_final` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`id`, `Kolor_id`, `Model_id`, `Typy_montazu_id`, `Materialy_id`, `Produkt_id`),
  INDEX `fk_Konfigurator_kolor_profili1_idx` (`Kolor_id` ASC),
  INDEX `fk_Konfigurator_Model_plisy1_idx` (`Model_id` ASC),
  INDEX `fk_Konfigurator_Typy_montazu1_idx` (`Typy_montazu_id` ASC),
  INDEX `fk_Konfigurator_Materialy1_idx` (`Materialy_id` ASC),
  INDEX `fk_Konfigurator_Produkt1_idx` (`Produkt_id` ASC),
  INDEX `fk_Konfigurator_Wycena1_idx` (`Wycena_cena_final` ASC),
  CONSTRAINT `fk_Konfigurator_kolor_profili1`
    FOREIGN KEY (`Kolor_id`)
    REFERENCES `mydb`.`Kolor_profili` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Konfigurator_Model_plisy1`
    FOREIGN KEY (`Model_id`)
    REFERENCES `mydb`.`Model_produktu` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Konfigurator_Typy_montazu1`
    FOREIGN KEY (`Typy_montazu_id`)
    REFERENCES `mydb`.`Typy_montazu` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Konfigurator_Materialy1`
    FOREIGN KEY (`Materialy_id`)
    REFERENCES `mydb`.`Materialy` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Konfigurator_Produkt1`
    FOREIGN KEY (`Produkt_id`)
    REFERENCES `mydb`.`Produkt` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Konfigurator_Wycena1`
    FOREIGN KEY (`Wycena_cena_final`)
    REFERENCES `mydb`.`Wycena` (`cena_final`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = 'grupymat_id';


-- -----------------------------------------------------
-- Table `mydb`.`Logowanie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Logowanie` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Logowanie` (
  `id` INT NOT NULL,
  `imie` VARCHAR(45) NULL,
  `nazwisko` VARCHAR(45) NULL,
  `login` VARCHAR(45) NULL,
  `password` VARCHAR(45) NOT NULL,
  `rola` VARCHAR(45) NULL,
  `id_roli` INT NULL,
  PRIMARY KEY (`id`));

USE `mydb`;

DELIMITER $$

USE `mydb`$$
DROP TRIGGER IF EXISTS `mydb`.`Wycena_BEFORE_INSERT` $$
USE `mydb`$$
CREATE TRIGGER `mydb`.`Wycena_BEFORE_INSERT`
BEFORE INSERT ON `Wycena` FOR EACH ROW 
BEGIN
SET NEW.data_wyceny=now();
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`Kolor_profili`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Kolor_profili` (`id`, `nazwy_k_p`, `doplata_do_k_p`) VALUES (1, 'Biały ', 0);
INSERT INTO `mydb`.`Kolor_profili` (`id`, `nazwy_k_p`, `doplata_do_k_p`) VALUES (2, 'Srebrny', 0);
INSERT INTO `mydb`.`Kolor_profili` (`id`, `nazwy_k_p`, `doplata_do_k_p`) VALUES (3, 'Brąz', 0);
INSERT INTO `mydb`.`Kolor_profili` (`id`, `nazwy_k_p`, `doplata_do_k_p`) VALUES (4, 'Sosna', 10.00);
INSERT INTO `mydb`.`Kolor_profili` (`id`, `nazwy_k_p`, `doplata_do_k_p`) VALUES (5, 'Złoty Dąb', 10.00);
INSERT INTO `mydb`.`Kolor_profili` (`id`, `nazwy_k_p`, `doplata_do_k_p`) VALUES (6, 'Orzech', 10.00);
INSERT INTO `mydb`.`Kolor_profili` (`id`, `nazwy_k_p`, `doplata_do_k_p`) VALUES (7, 'Mahoń', 10.00);
INSERT INTO `mydb`.`Kolor_profili` (`id`, `nazwy_k_p`, `doplata_do_k_p`) VALUES (8, 'Dąb bagienny', 10.00);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Model_produktu`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Model_produktu` (`id`, `nazwa_modelu`, `doplata_do_modelu`) VALUES (1, 'do okien pionowych', 0);
INSERT INTO `mydb`.`Model_produktu` (`id`, `nazwa_modelu`, `doplata_do_modelu`) VALUES (2, 'do okien dachowych', 15.00);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Typy_montazu`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Typy_montazu` (`id`, `nazwa_typu`, `doplata_m`) VALUES (1, 'Na listwy przyszybowe', 0);
INSERT INTO `mydb`.`Typy_montazu` (`id`, `nazwa_typu`, `doplata_m`) VALUES (2, 'Między listwy przyszybowe', 0);
INSERT INTO `mydb`.`Typy_montazu` (`id`, `nazwa_typu`, `doplata_m`) VALUES (3, 'Bezinwazyjnie', 20.00);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Materialy`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Materialy` (`id`, `nazwy_mat`, `doplata_mat`) VALUES (1, 'C01', 0);
INSERT INTO `mydb`.`Materialy` (`id`, `nazwy_mat`, `doplata_mat`) VALUES (2, 'C02', 0);
INSERT INTO `mydb`.`Materialy` (`id`, `nazwy_mat`, `doplata_mat`) VALUES (3, 'C05', 0);
INSERT INTO `mydb`.`Materialy` (`id`, `nazwy_mat`, `doplata_mat`) VALUES (4, 'C06', 0);
INSERT INTO `mydb`.`Materialy` (`id`, `nazwy_mat`, `doplata_mat`) VALUES (5, 'C08', 0);
INSERT INTO `mydb`.`Materialy` (`id`, `nazwy_mat`, `doplata_mat`) VALUES (6, 'SPARTA01', 20.00);
INSERT INTO `mydb`.`Materialy` (`id`, `nazwy_mat`, `doplata_mat`) VALUES (7, 'SPARTA02', 20.00);
INSERT INTO `mydb`.`Materialy` (`id`, `nazwy_mat`, `doplata_mat`) VALUES (8, 'SPARTA03', 20.00);
INSERT INTO `mydb`.`Materialy` (`id`, `nazwy_mat`, `doplata_mat`) VALUES (9, 'SPARTA04', 20.00);
INSERT INTO `mydb`.`Materialy` (`id`, `nazwy_mat`, `doplata_mat`) VALUES (10, 'SPARTA05', 20.00);
INSERT INTO `mydb`.`Materialy` (`id`, `nazwy_mat`, `doplata_mat`) VALUES (11, 'LUGO02', 30.00);
INSERT INTO `mydb`.`Materialy` (`id`, `nazwy_mat`, `doplata_mat`) VALUES (12, 'LUGO05', 30.00);
INSERT INTO `mydb`.`Materialy` (`id`, `nazwy_mat`, `doplata_mat`) VALUES (13, 'LUGO08', 30.00);
INSERT INTO `mydb`.`Materialy` (`id`, `nazwy_mat`, `doplata_mat`) VALUES (14, 'MOON 10240', 50.00);
INSERT INTO `mydb`.`Materialy` (`id`, `nazwy_mat`, `doplata_mat`) VALUES (15, 'MOON 10250', 50.00);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Produkt`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Produkt` (`id`, `nazwa`, `szer`, `wys`, `cenabazowa`, `ilosc`) VALUES (1, 'Żaluzja Plisowana', 50, 70, 50.00, NULL);
INSERT INTO `mydb`.`Produkt` (`id`, `nazwa`, `szer`, `wys`, `cenabazowa`, `ilosc`) VALUES (2, 'Żaluzja Plisowana', 50, 90, 70.00, NULL);
INSERT INTO `mydb`.`Produkt` (`id`, `nazwa`, `szer`, `wys`, `cenabazowa`, `ilosc`) VALUES (3, 'Żaluzja Plisowana', 50, 110, 90.00, NULL);
INSERT INTO `mydb`.`Produkt` (`id`, `nazwa`, `szer`, `wys`, `cenabazowa`, `ilosc`) VALUES (4, 'Żaluzja Plisowana', 50, 130, 110.00, NULL);
INSERT INTO `mydb`.`Produkt` (`id`, `nazwa`, `szer`, `wys`, `cenabazowa`, `ilosc`) VALUES (5, 'Żaluzja Plisowana', 50, 150, 130.00, NULL);
INSERT INTO `mydb`.`Produkt` (`id`, `nazwa`, `szer`, `wys`, `cenabazowa`, `ilosc`) VALUES (6, 'Żaluzja Plisowana', 70, 90, 80.00, NULL);
INSERT INTO `mydb`.`Produkt` (`id`, `nazwa`, `szer`, `wys`, `cenabazowa`, `ilosc`) VALUES (7, 'Żaluzja Plisowana', 70, 110, 100.00, NULL);
INSERT INTO `mydb`.`Produkt` (`id`, `nazwa`, `szer`, `wys`, `cenabazowa`, `ilosc`) VALUES (8, 'Żaluzja Plisowana', 70, 130, 120.00, NULL);
INSERT INTO `mydb`.`Produkt` (`id`, `nazwa`, `szer`, `wys`, `cenabazowa`, `ilosc`) VALUES (9, 'Żaluzja Plisowana', 70, 150, 140.00, NULL);
INSERT INTO `mydb`.`Produkt` (`id`, `nazwa`, `szer`, `wys`, `cenabazowa`, `ilosc`) VALUES (10, 'Żaluzja Plisowana', 80, 100, 90.00, NULL);
INSERT INTO `mydb`.`Produkt` (`id`, `nazwa`, `szer`, `wys`, `cenabazowa`, `ilosc`) VALUES (11, 'Żaluzja Plisowana', 80, 120, 110.00, NULL);
INSERT INTO `mydb`.`Produkt` (`id`, `nazwa`, `szer`, `wys`, `cenabazowa`, `ilosc`) VALUES (12, 'Żaluzja Plisowana', 80, 140, 130.00, NULL);
INSERT INTO `mydb`.`Produkt` (`id`, `nazwa`, `szer`, `wys`, `cenabazowa`, `ilosc`) VALUES (13, 'Żaluzja Plisowana', 80, 160, 150.00, NULL);
INSERT INTO `mydb`.`Produkt` (`id`, `nazwa`, `szer`, `wys`, `cenabazowa`, `ilosc`) VALUES (14, 'Żaluzja Plisowana', 80, 180, 170.00, NULL);
INSERT INTO `mydb`.`Produkt` (`id`, `nazwa`, `szer`, `wys`, `cenabazowa`, `ilosc`) VALUES (15, 'Żaluzja Plisowana', 80, 200, 190.00, NULL);
INSERT INTO `mydb`.`Produkt` (`id`, `nazwa`, `szer`, `wys`, `cenabazowa`, `ilosc`) VALUES (16, 'Żaluzja Plisowana', 80, 220, 210.00, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Logowanie`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Logowanie` (`id`, `imie`, `nazwisko`, `login`, `password`, `rola`, `id_roli`) VALUES (1, 'Marian', 'Kowalski', 'mkowalski', 'anakonda', 'user', 1);
INSERT INTO `mydb`.`Logowanie` (`id`, `imie`, `nazwisko`, `login`, `password`, `rola`, `id_roli`) VALUES (2, 'Andrzej', 'Duda', 'aduda', 'narty', 'admin', 0);
INSERT INTO `mydb`.`Logowanie` (`id`, `imie`, `nazwisko`, `login`, `password`, `rola`, `id_roli`) VALUES (3, 'Magdalena', 'Ogórek', 'mogorek', 'gorzki', 'admin', 0);
INSERT INTO `mydb`.`Logowanie` (`id`, `imie`, `nazwisko`, `login`, `password`, `rola`, `id_roli`) VALUES (4, 'Paweł', 'Kukiz', 'pkukiz', 'piersi', 'user', 1);
INSERT INTO `mydb`.`Logowanie` (`id`, `imie`, `nazwisko`, `login`, `password`, `rola`, `id_roli`) VALUES (5, 'Janusz', 'Palikot', 'jpalikot', 'wodka', 'user', 1);

COMMIT;

